apiVersion: v1
kind: Namespace
metadata:
  name: robo-world
---
apiVersion: v1
kind: Secret
metadata:
  name: robo-world-secrets
  namespace: robo-world
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@robo-world-postgres:5432/{{ .Values.postgres.database }}?schema=public"
