apiVersion: v1
kind: Namespace
metadata:
  name: electron
---
apiVersion: v1
kind: Secret
metadata:
  name: electron-secrets
  namespace: electron
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@electron-postgres:5432/{{ .Values.postgres.database }}?schema=public"
